# Generated by Django 3.0.3 on 2020-06-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200)),
                ('links', models.CharField(max_length=200, null=True)),
                ('siteorigin', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
