# Generated by Django 3.0.3 on 2020-06-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200)),
                ('siteorigin', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='links',
            name='links',
        ),
        migrations.RemoveField(
            model_name='links',
            name='siteorigin',
        ),
        migrations.RemoveField(
            model_name='links',
            name='user',
        ),
        migrations.AddField(
            model_name='links',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
