# Generated by Django 3.0.3 on 2020-06-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchstore', '0002_auto_20200623_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='siteorigin',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='site',
            name='user',
        ),
        migrations.AddField(
            model_name='site',
            name='Type',
            field=models.CharField(choices=[('Shopify', 'Shopify'), ('Shopify Plus', 'Shopify Plus')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Urls',
            field=models.TextField(null=True),
        ),
    ]
