# Generated by Django 3.0.3 on 2020-06-24 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searchstore', '0003_auto_20200623_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='crawledData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='site',
            name='Type',
            field=models.CharField(choices=[('Shopify', 'Shopify'), ('Shopify Plus', 'Shopify Plus'), ('BigCommerce', 'BigCommerce'), ('Demandware', 'Demandware')], max_length=200, null=True),
        ),
    ]
