# Generated by Django 3.0.3 on 2020-06-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchstore', '0004_auto_20200624_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawleddata',
            options={},
        ),
        migrations.RenameField(
            model_name='site',
            old_name='Name',
            new_name='Container_Image_URL_Path_Class',
        ),
        migrations.RemoveField(
            model_name='crawleddata',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='crawleddata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='crawleddata',
            name='title',
        ),
        migrations.RemoveField(
            model_name='crawleddata',
            name='url',
        ),
        migrations.RemoveField(
            model_name='site',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='site',
            name='Urls',
        ),
        migrations.AddField(
            model_name='crawleddata',
            name='Product_Image_Link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crawleddata',
            name='Product_Link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='crawleddata',
            name='Product_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crawleddata',
            name='Product_Price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='crawleddata',
            name='Product_Website_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Container_Image_URL_Path_Type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Container_Name_Path_Class',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Container_Name_Path_Type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Container_Price_Path_Class',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Container_Price_Path_Type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Container_Product_URL_Path_Class',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Container_Product_URL_Path_Type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Number_of_Pages',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Product_HTMLCard_Path_Class',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Product_HTMLCard_Path_Type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Product_Page_URL_p1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Product_Page_URL_p2_ifneeded',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Website_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='Website_Type',
            field=models.CharField(choices=[('Shopify', 'Shopify'), ('WooCommerce', 'WooCommerce'), ('BigCommerce', 'BigCommerce'), ('Demandware', 'Demandware')], max_length=200, null=True),
        ),
    ]
