# Generated by Django 3.0.3 on 2020-06-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchstore', '0005_auto_20200626_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crawledData',
        ),
    ]
