# Generated by Django 3.0.3 on 2020-06-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchstore', '0006_delete_crawleddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='crawledData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=200, null=True)),
                ('Product_Price', models.FloatField(null=True)),
                ('Product_Link', models.URLField(null=True)),
                ('Product_Image_Link', models.CharField(max_length=200, null=True)),
                ('Product_Website_Name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
