# Generated by Django 3.0.3 on 2020-06-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchstore', '0007_crawleddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='Root_URL',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
