# Generated by Django 3.0.3 on 2020-06-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchstore', '0008_site_root_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleddata',
            name='Product_Image_Link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='crawleddata',
            name='Product_Link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='crawleddata',
            name='Product_Name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='crawleddata',
            name='Product_Price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crawleddata',
            name='Product_Website_Name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='Product_Page_URL_p1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='Root_URL',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
