# Generated by Django 3.0.3 on 2020-07-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchstore', '0010_auto_20200629_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleddata',
            name='Product_Image_Link',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
